name: 'Terraform CD'

on:
  workflow_dispatch:
    inputs:
      event_type:
        description: Update Terraform
        required: true

jobs:
  terraform:
    name: 'Updating Terraform and deploying to Azure'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUB_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT }}
      TF_VAR_AZURE_SUB_ID_SECRET: ${{ secrets.AZURE_SUB_ID }}
      TF_VAR_AZURE_TENANT_ID_SECRET: ${{ secrets.AZURE_TENANT }}
      TF_VAR_AZURE_CLIENT_ID_SECRET: ${{ secrets.AZURE_CLIENT_ID }}
      TF_VAR_AZURE_CLIENT_SECRET_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      TF_VAR_SOURCE_PAT: ${{ secrets.SOURCE_PAT }}
      TF_VAR_SOURCE_PAT_ME: ${{ secrets.SOURCE_PAT_ME }}

    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Terraform Repository
        uses: actions/checkout@v2
        with:
          repository: Labb3PubliceringSnitches/Terraform

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      -name: Upload to blob storage
       run: |
          az storage blob upload --account-name snitchedstate --container-name statecontainer --name tfplan --connection-string "DefaultEndpointsProtocol=https;AccountName=snitchedstate;AccountKey=g2SEECR93QBJdFaru+BM6oQyJOWTt5Vh/5htsIH3VkO+L3E3iPVHv42DkZrX8egDZZ3CP+Ubhw8I+AStyeKP2w==;EndpointSuffix=core.windows.net"


      - name: Remove Plan File
        run: rm tfplan