name: Terraform CD

on:
  workflow_dispatch:
    inputs:
      event_type:
        description: Update Terraform
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TF_VAR_AZURE_SUB_ID_SECRET: ${{ secrets.AZURE_SUB_ID }}
      TF_VAR_AZURE_TENANT_ID_SECRET: ${{ secrets.AZURE_TENANT }}
      TF_VAR_AZURE_CLIENT_ID_SECRET: ${{ secrets.AZURE_CLIENT_ID }}
      TF_VAR_AZURE_CLIENT_SECRET_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      TF_VAR_SOURCE_PAT: ${{ secrets.SOURCE_PAT }}
      

    steps:
      - name: Download Blob
        run: |
          az storage blob download --account-name TFSTATESTORAGE --container-name snitchedstate --name terraform.tfstate --connection-string "DefaultEndpointsProtocol=https;AccountName=snitchedstate;AccountKey=g2SEECR93QBJdFaru+BM6oQyJOWTt5Vh/5htsIH3VkO+L3E3iPVHv42DkZrX8egDZZ3CP+Ubhw8I+AStyeKP2w==;EndpointSuffix=core.windows.net"


      - name: Checkout Terraform Repository
        uses: actions/checkout@v2
        with:
          repository: Labb3PubliceringSnitches/Terraform

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="resource_group_name=Labb3-Snitches-RG" \
            -backend-config="storage_account_name=snitchedstate" \
            -backend-config="container_name=statecontainer" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="client_id=${{ secrets.AZURE_CLIENT_ID }}" \
            -backend-config="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \
            -backend-config="tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
            -backend-config="subscription_id=${{ secrets.AZURE_SUB_ID }}"

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Remove Plan File
        run: rm tfplan