name: 'Terraform CD'

on:
  repository_dispatch:
    types:
      - push-to-repo

jobs:
  terraform:
    name: 'Updating Terraform and deploying to Azure'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUB_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT }}
      TF_VAR_AZURE_SUB_ID_SECRET: ${{ secrets.AZURE_SUB_ID }}
      TF_VAR_AZURE_TENANT_ID_SECRET: ${{ secrets.AZURE_TENANT }}
      TF_VAR_AZURE_CLIENT_ID_SECRET: ${{ secrets.AZURE_CLIENT_ID }}
      TF_VAR_AZURE_CLIENT_SECRET_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      TF_VAR_SOURCE_PAT: ${{ secrets.SOURCE_PAT }}
      TF_VAR_SOURCE_PAT_ME: ${{ secrets.SOURCE_PAT_ME }}

    runs-on: ubuntu-latest
    concurrency:
      group: terraform-lock
      cancel-in-progress: true  # This ensures that previous runs are canceled when a new one starts
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Terraform Repository
        uses: actions/checkout@v3
        with:
          repository: Labb3PubliceringSnitches/Terraform

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Terraform Plan
        run: terraform plan -out main.tfplan

      - name: Terraform Apply
        run: terraform apply "main.tfplan"

      - name: Remove Plan File
        run: rm main.tfplan
        
      - name: Cleanup Workflow Lock File
        run: |
          rm -f workflow.lock
      
      # - name: Authenticate Azure CLI with Service Principal
      #   run: |
      #     az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT }}
      #     az account set --subscription ${{ secrets.AZURE_SUB_ID }}

      # - name: Restart Azure Web App
      #   run: |
      #     az webapp restart --name Snitches --resource-group labb3-snitches-rg
